### ISSUE TITLE
Please release a new version with the fix for openssl 1.1.1 #1

### ISSUE THREAD

**Issue by platy** [expo/expo-server-sdk-rust#5]
Issue #1  is fixed on master but that hasn't yet been released, this prevents users of the library from being able to build on systems with openssl 1.1.1, causing users to have to downgrade openssl in order to build.

Please release a new version to crates.io.

**Comment by jonsamp** [comment]
Hi @platy --Sorry that we missed your issue. I know it's been years. We now are recommending this Rust library for push notifications. If you still need it, I hope it helps you. https://github.com/katayama8000/expo-push-notification-client-rust
