### ISSUE TITLE
Is this depreciated?

### ISSUE THREAD

**Issue by spencerbart** [expo/expo-server-sdk-rust#6]
Just want to make sure this is still working before I start building out the server with this

**Comment by spencerbart** [comment]
This should be upgraded or marked as depreciated

**Comment by jonsamp** [comment]
This library is deprecated. I just made a PR to make a note in the README.

We now are recommending this Rust library for push notifications. If you still need it, I hope it helps you. https://github.com/katayama8000/expo-push-notification-client-rust

**Comment by jonsamp** [comment]
This library is deprecated. I just made a PR to make a note in the README.

We now are recommending this Rust library for push notifications. If you still need it, I hope it helps you. https://github.com/katayama8000/expo-push-notification-client-rust
