### ISSUE TITLE
Update this crate or deprecate it

### ISSUE THREAD

**Issue by GPeaky** [expo/expo-server-sdk-rust#8]
Hi, this crate have not been updated for almost 5 years, some people send pull requests to update it, but you did't even see it. If you don't want to update the crate please deprecate and let people create another one by the community.

**Comment by jonsamp** [comment]
This library is deprecated. I just made a PR to make a note in the README.

We now are recommending this Rust library for push notifications. If you still need it, I hope it helps you. https://github.com/katayama8000/expo-push-notification-client-rust
