### ISSUE TITLE
 I have created a new expo-server-sdk 🥳🥳🥳

### ISSUE THREAD

**Issue by katayama8000** [expo/expo-server-sdk-rust#9]
I have created a new expo-server-sdk. It works with the latest version of Rust as well. Please give it a try!
https://github.com/katayama8000/expo-push-notification-client-rust

**Comment by katayama8000** [comment]
https://crates.io/crates/expo_push_notification_client

**Comment by jonsamp** [comment]
Hi @katayama8000, I just made a couple PRs to recommend your library. Thanks for creating it. We are excited to recommend it.

I am going to close this PR and get your library merged into our docs/recommended in this repo. Here are the PRs I have opened to make those changes:

- https://github.com/expo/expo/pull/27116
- https://github.com/expo/expo-server-sdk-rust/pull/10
